### ISSUE TITLE
Can't download files through the provided script

### ISSUE THREAD

**Issue by arthurtofani** [MTG/da-tacos#2]
Hi,

I'm trying to download the dataset using the provided script and I'm getting a message saying that the file needs more permissions for this action, as seen above. Through google drive website the link is working fine, though. Permissions seem to be correctly set as well.

```
# python download_da-tacos.py --dataset benchmark --outputdir /dataset --unpack --remove

Downloading single_files folder for the benchmark subset
Permission denied: https://drive.google.com/uc?id=1eiOI3fyxiZsje7AVmsA46kJzTwpQB09h
Maybe you need to change permission over 'Anyone with the link'?
Unpacking the zip file /dataset/da-tacos_benchmark_subset_single_files.zip into /dataset
Traceback (most recent call last):
  File "download_da-tacos.py", line 125, in <module>
    download(args.dataset, args.type, args.source, args.outputdir, args.unpack, args.remove)
  File "download_da-tacos.py", line 70, in download
    unpack_zip(output, output_dir)
  File "download_da-tacos.py", line 77, in unpack_zip
    with ZipFile(output, 'r') as z:
  File "/usr/local/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/dataset/da-tacos_benchmark_subset_single_files.zip'
```

**Comment by furkanyesiler** [comment]
Hello Arthur! Thanks for your interest in Da-TACOS.

I just tried the same command as in your post and I had the same problem. When I open that link in a browser, I see that Google Drive has some daily limitations on downloads (the message I see is "Sorry, you can't view or download this file at this time.").

On the other hand, for other files, it still works (for example, if you would try passing the argument `--type crema`, it starts downloading). Unfortunately, only solution that I see is to try again the next day. I know it can be inconvenient but let me know if there's anything else I can do. 

I have been delaying putting the files on zenodo but I'll get to that as soon as possible, now that I know we need it for sure. Thanks for bringing this up.

**Comment by leonardltk** [comment]
Are there updates for putting the files up in zenodo ?

**Comment by furkanyesiler** [comment]
Hi @leonardltk!

We hope that by next week, they will be available through Zenodo. I'll post an update on this issue.
