### ISSUE TITLE
KeyError: 'benchmark subset'

### ISSUE THREAD

**Issue by leonardltk** [MTG/da-tacos#3]
Hi, 

I am trying to download the dataset, I ran this code
```python
python download_da-tacos.py \
    --dataset da-tacos \
    --outputdir data
```

This is the error i received.
```python
Downloading single_files folder for the benchmark subset subset
Traceback (most recent call last):
  File "download_da-tacos.py", line 125, in <module>
    download(args.dataset, args.type, args.source, args.outputdir, args.unpack, args.remove)
  File "download_da-tacos.py", line 60, in download
    output = os.path.join(output_dir, download_paths[subset][feature]['filename'])
KeyError: 'benchmark subset'
```

I see you included `'benchmark subset'` at line 21, is it not supposed to be there?
```python
    if dataset == 'da-tacos':
        download_sets = ['benchmark subset', 'cover analysis subset', 'metadata']
```

**Comment by furkanyesiler** [comment]
Hi @leonardltk!

Thanks for pointing that out, it was an error from our side. I recently pushed the corrected version.
